apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  namespace: kube-system
spec: 
  containers: 
    - name: frontend
      image: nginx
      volumeMounts: 
      - mountPath: "/var/www/html"
        name: test-vol01

  volumes:
    - name: test-vol01
      persistentVolumeClaim: 
        claimName: test-vol01-pvc
