apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
spec: 
  containers: 
    - name: frontend
      image: nginx
      volumeMounts: 
      - mountPath: "/var/www/html"
        name: test-vol01-nginx

  volumes:
    - name: test-vol01-nginx
      persistentVolumeClaim: 
        claimName: myclaim
