apiVersion: v1
kind: Pod
metadata:
  name: mypod 
spec: 
  containers: 
    - name: frontend
      image: nginx
      volumeMounts: 
      - mountPath: "/var/www/html"
        name: pv-vol01

  volumes:
    - name: pv-vol01
      persistentVolumeClaim: 
        claimName: myclaim
