apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
spec:
  containers:
    - name: app-test
      image: httpd
      volumeMounts:
        - name: nfs-volume
          mountPath: /conf # Please change the destination you like the share to be mounted too
  volumes:
    - name: nfs-volume
      nfs:
        server: 192.168.9.10  # NFS Server Ip address 
        path: /conf  # NFS Server share location
