apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-vol-pvc
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: longhorn-vol-pv
  storageClassName: longhorn
