apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: http-server
spec:
<<<<<<< HEAD
  replicas: 3
=======
  replicas: 1
>>>>>>> 0e69ddfc8cb3d4ab0ba6e0def4446a098b1a94cc
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
<<<<<<< HEAD
        image: httpd:latest
=======
        image: httpd
>>>>>>> 0e69ddfc8cb3d4ab0ba6e0def4446a098b1a94cc
        ports:
        - containerPort: 80
