apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: httpd-ingress
spec:
  rules:
  - host: httpd.com
    http: 
      paths:
      - backend: 
          serviceName: httpd-service
          servicePort: 8081
