apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-fanout-example
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        pathType: Prefix
        backend:
          service:
            name: httpd-nodeport-service
            port:
              number: 8080
      - path: /bar
        pathType: Prefix
        backend:
          service:
            name: httpd-nodeport-service-one
            port:
              number: 8081