apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      volumes:
      - name: config
        hostPath:
          path: /srv/gitlab/config
          type: Directory
      - name: logs
        hostPath:
          path: /srv/gitlab/logs
          type: Directory
      - name: data
        hostPath:
          path: /srv/gitlab/data
          type: Directory	  
      containers:
        - image: gitlab/gitlab-ce:latest
          name: gitlab
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
          - name: config
            mountPath: /etc/gitlab
          - name: logs
            mountPath: /var/log/gitlab
          - name: data
            mountPath: /var/opt/gitlab
