apiVersion: v1
kind: Pod
metadata:
  name: pod-for-secrets
spec:
  containers:
  - name: mypod
    image: redis
    env: 
      - name: SECRET_USERNAME
        valueFrom: 
          secretKeyRef:
            name: idpassword
            key: username
      - name: SECRET_PASSWORD
        valueFrom: 
          secretKeyRef:
            name: idpassword
            key: password
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret