###########################
#type - Service Token Secret
###########################
apiVersion: v1
kind: Secret
metadata:
  name: secret-serviceaccount-sample
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: kubernetes.io/service-account-token
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  extra: YmFyCg==

###################
# type - Basic-Auth
##################
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: t0p-Secret

######################
#Type - TLS
######################
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-ssh-auth
type: kubernetes.io/ssh-auth
data:
  # the data is abbreviated in this example
  ssh-privatekey: |
          MIIEpQIBAAKCAQEAulqb

######################
#Type - TLS
######################
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
type: kubernetes.io/tls
data:
  # the data is abbreviated in this example
  tls.crt: |
        MIIEpQIBAAKCAQEAulqb
  tls.key: |
        MIIEpQIBAAKCAQEAulqb

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  # the data is abbreviated in this example
  foo: |
        MIIEpQIBAAKCAQEAulqb
---
apiVersion: v1
kind: Secret
metadata:
  name: idpassword
type: Opaque
data:
  # the data is abbreviated in this example
  password: dmFsdWUtMg0KDQo=
  username: dmFsdWUtMQ0K